#!/usr/bin/env node
/**
 * roland init — Set up Roland in any project directory.
 *
 * Usage:
 *   npx roland init                  # init current directory
 *   npx roland init /path/to/project # init a specific directory
 *
 * Or from the roland repo:
 *   npx tsx scripts/init.ts [target-dir]
 *
 * What it does:
 *   1. Exports agent configs (.github/agents/, .cursor/rules/)
 *   2. Generates IDE MCP configs (.vscode/mcp.json, .cursor/mcp.json)
 *      with absolute paths pointing back to this Roland installation
 *   3. Generates .github/copilot-instructions.md
 *   4. Scaffolds roland-context.json + MIGRATION.md (skips if already present)
 *   5. Scaffolds .roland/ directory + project-context.json
 */

import { execSync } from 'child_process';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rolandRoot = path.resolve(__dirname, '..');

function main() {
  const targetDir = process.argv[2]
    ? path.resolve(process.argv[2])
    : process.cwd();

  // Verify roland is built
  const distIndex = path.join(rolandRoot, 'dist', 'index.js');
  if (!fs.existsSync(distIndex)) {
    console.error('❌ Roland is not built. Run this first:');
    console.error(`   cd ${rolandRoot} && npm run build`);
    process.exit(1);
  }

  console.log(`\n🤖 Roland Init`);
  console.log(`   Roland:   ${rolandRoot}`);
  console.log(`   Target:   ${targetDir}\n`);

  // Run export-ide-configs with --target
  const exportScript = path.join(rolandRoot, 'scripts', 'export-ide-configs.ts');
  try {
    execSync(
      `npx tsx "${exportScript}" --target "${targetDir}"`,
      { cwd: rolandRoot, stdio: 'inherit' }
    );
  } catch (err) {
    console.error('\n❌ Init failed. See errors above.');
    process.exit(1);
  }

  // ── Step 4: Scaffold roland-context.json + MIGRATION.md ──────────────────
  const contextJsonPath = path.join(targetDir, 'roland-context.json');
  const migrationMdPath = path.join(targetDir, 'MIGRATION.md');

  if (!fs.existsSync(contextJsonPath)) {
    const projectName = path.basename(targetDir);
    const now = new Date().toISOString();
    const defaultCtx = {
      schemaVersion: '1.0',
      project: {
        name: projectName,
        sourceLanguage: 'VB6',
        targetLanguage: 'C#',
        description: `Legacy VB6 to modern C# migration for ${projectName}`,
        createdAt: now,
        lastUpdated: now,
      },
      rules: [],
      decisions: [],
      testPatterns: [],
      customSections: {},
    };
    fs.writeFileSync(contextJsonPath, JSON.stringify(defaultCtx, null, 2), 'utf-8');
    console.log(`   ✅ Created roland-context.json`);
  } else {
    console.log(`   ⏭️  roland-context.json already exists — skipping`);
  }

  if (!fs.existsSync(migrationMdPath)) {
    const projectName = path.basename(targetDir);
    const mdContent = [
      `# MIGRATION.md`,
      `> Auto-generated by Roland. Edit \`roland-context.json\` or use the \`update_migration_context\` MCP tool.`,
      ``,
      `## Project`,
      `| Field | Value |`,
      `|---|---|`,
      `| Name | ${projectName} |`,
      `| Source | VB6 |`,
      `| Target | C# |`,
      ``,
      `## VB6→C# Mapping Rules`,
      `_No rules yet. Use \`update_migration_context\` with \`type=rule\` to add them._`,
      ``,
      `## Past Decisions`,
      `_No decisions recorded yet._`,
      ``,
      `## Test Patterns`,
      `_No test patterns recorded yet._`,
      ``,
    ].join('\n');
    fs.writeFileSync(migrationMdPath, mdContent, 'utf-8');
    console.log(`   ✅ Created MIGRATION.md`);
  } else {
    console.log(`   ⏭️  MIGRATION.md already exists — skipping`);
  }

  // ── Step 5: Scaffold .roland/ directory + project-context.json ───────────
  const rolandDir = path.join(targetDir, '.roland');
  if (!fs.existsSync(rolandDir)) {
    fs.mkdirSync(rolandDir, { recursive: true });
  }
  const projectContextPath = path.join(rolandDir, 'project-context.json');
  if (!fs.existsSync(projectContextPath)) {
    const defaultContext = {
      version: '1.0',
      project: {
        name: path.basename(targetDir),
      },
      conventions: [],
      patterns: [],
      decisions: [],
      errors: [],
      last_updated: new Date().toISOString(),
    };
    fs.writeFileSync(projectContextPath, JSON.stringify(defaultContext, null, 2), 'utf-8');
    console.log(`   ✅ Created .roland/project-context.json`);
  } else {
    console.log(`   ⏭️  .roland/project-context.json already exists — skipping`);
  }

  const modelQualityPath = path.join(rolandDir, 'model-quality.json');
  if (!fs.existsSync(modelQualityPath)) {
    fs.writeFileSync(modelQualityPath, '[]', 'utf-8');
    console.log(`   ✅ Created .roland/model-quality.json`);
  } else {
    console.log(`   ⏭️  .roland/model-quality.json already exists — skipping`);
  }

  console.log(`   💡 Add .roland/ and .roland-sim/ to your .gitignore`);

  ensureGitignoreEntries(targetDir, ['.roland/', '.roland-sim/']);

  console.log(`\n🎉 Roland is ready in ${targetDir}`);
  console.log(`\nNext steps:`);
  console.log(`  1. Open ${targetDir} in Cursor or VS Code`);
  console.log(`  2. Verify MCP server: Settings → MCP (Cursor) or MCP: List Servers (VS Code)`);
  console.log(`  3. In chat, try: "Use the health_check tool"`);
  console.log(`  4. Edit roland-context.json to add your VB6→C# mapping rules`);
  console.log(`     or use: update_migration_context type=rule pattern=... replacement=...`);
  console.log(`  5. For multi-step work, use: roland team "your goal" --loop-template full-cycle-verified-loop`);
}

function ensureGitignoreEntries(targetDir: string, entries: string[]): void {
  const gitignorePath = path.join(targetDir, '.gitignore');
  let content = '';
  try {
    content = fs.existsSync(gitignorePath) ? fs.readFileSync(gitignorePath, 'utf-8') : '';
  } catch {
    content = '';
  }
  const missing = entries.filter((e) => !content.includes(e));
  if (missing.length === 0) return;
  const block = '\n# Roland local mission state\n' + missing.join('\n') + '\n';
  fs.appendFileSync(gitignorePath, block, 'utf-8');
  console.log(`   ✅ Updated .gitignore (${missing.join(', ')})`);
}

main();
