#!/usr/bin/env node
/**
 * roland init — Set up Roland in any project directory.
 *
 * Usage:
 *   npx roland init                  # init current directory
 *   npx roland init /path/to/project # init a specific directory
 *
 * Or from the roland repo:
 *   npx tsx scripts/init.ts [target-dir]
 *
 * What it does:
 *   1. Exports agent configs (.github/agents/, .cursor/rules/)
 *   2. Generates IDE MCP configs (.vscode/mcp.json, .cursor/mcp.json)
 *      with absolute paths pointing back to this Roland installation
 *   3. Generates .github/copilot-instructions.md
 *   4. Scaffolds roland-context.json + MIGRATION.md (skips if already present)
 *   5. Generates .goose/config.yaml with auto context-load hook
 */

import { execSync } from 'child_process';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rolandRoot = path.resolve(__dirname, '..');

function main() {
  const targetDir = process.argv[2]
    ? path.resolve(process.argv[2])
    : process.cwd();

  // Verify roland is built
  const distIndex = path.join(rolandRoot, 'dist', 'index.js');
  if (!fs.existsSync(distIndex)) {
    console.error('❌ Roland is not built. Run this first:');
    console.error(`   cd ${rolandRoot} && npm run build`);
    process.exit(1);
  }

  console.log(`\n🤖 Roland Init`);
  console.log(`   Roland:   ${rolandRoot}`);
  console.log(`   Target:   ${targetDir}\n`);

  // Run export-ide-configs with --target
  const exportScript = path.join(rolandRoot, 'scripts', 'export-ide-configs.ts');
  try {
    execSync(
      `npx tsx "${exportScript}" --target "${targetDir}"`,
      { cwd: rolandRoot, stdio: 'inherit' }
    );
  } catch (err) {
    console.error('\n❌ Init failed. See errors above.');
    process.exit(1);
  }

  // ── Step 4: Scaffold roland-context.json + MIGRATION.md ──────────────────
  const contextJsonPath = path.join(targetDir, 'roland-context.json');
  const migrationMdPath = path.join(targetDir, 'MIGRATION.md');

  if (!fs.existsSync(contextJsonPath)) {
    const projectName = path.basename(targetDir);
    const now = new Date().toISOString();
    const defaultCtx = {
      schemaVersion: '1.0',
      project: {
        name: projectName,
        sourceLanguage: 'VB6',
        targetLanguage: 'C#',
        description: `Legacy VB6 to modern C# migration for ${projectName}`,
        createdAt: now,
        lastUpdated: now,
      },
      rules: [],
      decisions: [],
      testPatterns: [],
      customSections: {},
    };
    fs.writeFileSync(contextJsonPath, JSON.stringify(defaultCtx, null, 2), 'utf-8');
    console.log(`   ✅ Created roland-context.json`);
  } else {
    console.log(`   ⏭️  roland-context.json already exists — skipping`);
  }

  if (!fs.existsSync(migrationMdPath)) {
    const projectName = path.basename(targetDir);
    const mdContent = [
      `# MIGRATION.md`,
      `> Auto-generated by Roland. Edit \`roland-context.json\` or use the \`update_migration_context\` MCP tool.`,
      ``,
      `## Project`,
      `| Field | Value |`,
      `|---|---|`,
      `| Name | ${projectName} |`,
      `| Source | VB6 |`,
      `| Target | C# |`,
      ``,
      `## VB6→C# Mapping Rules`,
      `_No rules yet. Use \`update_migration_context\` with \`type=rule\` to add them._`,
      ``,
      `## Past Decisions`,
      `_No decisions recorded yet._`,
      ``,
      `## Test Patterns`,
      `_No test patterns recorded yet._`,
      ``,
    ].join('\n');
    fs.writeFileSync(migrationMdPath, mdContent, 'utf-8');
    console.log(`   ✅ Created MIGRATION.md`);
  } else {
    console.log(`   ⏭️  MIGRATION.md already exists — skipping`);
  }

  // ── Step 5: .goose/config.yaml with auto context-load hook ───────────────
  const gooseDir = path.join(targetDir, '.goose');
  const gooseConfig = path.join(gooseDir, 'config.yaml');

  if (!fs.existsSync(gooseDir)) fs.mkdirSync(gooseDir, { recursive: true });

  if (!fs.existsSync(gooseConfig)) {
    const distIndexPath = path.join(rolandRoot, 'dist', 'index.js').replace(/\\/g, '/');
    // Read roland-context.json to embed directly in the system prompt
    // so every Goose session starts with full project context automatically
    let embeddedContext = '';
    if (fs.existsSync(contextJsonPath)) {
      try {
        const ctx = JSON.parse(fs.readFileSync(contextJsonPath, 'utf-8'));
        const parts: string[] = [];
        if (ctx.project) {
          parts.push(`Project: ${ctx.project.name} (${ctx.project.sourceLanguage} → ${ctx.project.targetLanguage})`);
          if (ctx.project.description) parts.push(`Description: ${ctx.project.description}`);
        }
        if (ctx.rules?.length) {
          parts.push(`\n### Mapping Rules (${ctx.rules.length} total)`);
          for (const r of ctx.rules) parts.push(`- ${r.pattern} → ${r.replacement}${r.notes ? ` (${r.notes})` : ''}`);
        }
        if (ctx.decisions?.length) {
          parts.push(`\n### Past Decisions (${ctx.decisions.length} total)`);
          for (const d of ctx.decisions) parts.push(`- ${d.description}: ${d.rationale}`);
        }
        if (ctx.testPatterns?.length) {
          parts.push(`\n### Test Patterns (${ctx.testPatterns.length} total)`);
          for (const t of ctx.testPatterns) parts.push(`- ${t.name}: ${t.description}`);
        }
        if (parts.length > 1) embeddedContext = parts.join('\n');
      } catch {
        // If parsing fails, context will be loaded via tool call fallback
      }
    }

    const contextSection = embeddedContext
      ? [
          ``,
          `      ## Project Context (auto-loaded from roland-context.json)`,
          `      ${embeddedContext.split('\n').join('\n      ')}`,
          ``,
          `      This context is auto-injected. Call load_migration_context to refresh`,
          `      if you've updated rules mid-session.`,
        ].join('\n')
      : [
          ``,
          `      ## Session start (always do this first)`,
          `      Call load_migration_context (init_session: true) and use the returned`,
          `      context_block as your working knowledge for this session.`,
        ].join('\n');

    const gooseYaml = [
      `# .goose/config.yaml — Roland + Goose coding agent`,
      `# Auto-generated by: npx roland init`,
      `#`,
      `# Wires Roland (smart routing + context) alongside Goose's Developer extension`,
      `# (file read/write + shell) so every session is a full coding agent.`,
      `#`,
      `# Project context from roland-context.json is embedded below so every session`,
      `# starts with the full playbook — no manual tool call needed.`,
      ``,
      `extensions:`,
      `  developer:`,
      `    name: Developer`,
      `    type: builtin`,
      `    enabled: true`,
      ``,
      `  roland:`,
      `    name: Roland`,
      `    type: stdio`,
      `    cmd: node`,
      `    args:`,
      `      - "${distIndexPath}"`,
      `    enabled: true`,
      `    timeout: 300`,
      `    envs:`,
      `      ROLAND_PROJECT_ROOT: "${targetDir.replace(/\\/g, '/')}"`,
      `    instructions: |`,
      `      You are a coding agent with two capability layers:`,
      `      1. Developer extension — read/write files and run shell commands directly.`,
      `      2. Roland MCP tools — smart model routing, cost tracking, and project context.`,
      contextSection,
      ``,
      `      ## Before significant coding work`,
      `      Call triage with the user's message to get agent + recipe recommendations.`,
      `      Call route_model to select the cheapest adequate model for the task complexity.`,
      ``,
      `      ## While working`,
      `      Use text_editor to read and edit files. Use shell to run builds, tests, and`,
      `      linters. Fix failures autonomously — do not ask the user to run commands.`,
      ``,
      `      ## When you discover a new pattern`,
      `      Call update_migration_context (type=rule or type=decision) to persist it.`,
      `      The returned updated_context_block reflects the updated playbook.`,
      ``,
      `      ## After each model response`,
      `      Call track_cost with the model, input_tokens, and output_tokens.`,
      ``,
      `      ## For large multi-step tasks`,
      `      Call run_goose_task to spawn a focused sub-session with its own file context.`,
      `      Or use start_recipe / advance_recipe to drive a multi-agent workflow.`,
    ].join('\n');
    fs.writeFileSync(gooseConfig, gooseYaml, 'utf-8');
    console.log(`   ✅ Created .goose/config.yaml`);
  } else {
    console.log(`   ⏭️  .goose/config.yaml already exists — skipping`);
  }

  // ── Step 6: Scaffold .roland-permissions.json ────────────────────────────
  const permissionsPath = path.join(targetDir, '.roland-permissions.json');
  if (!fs.existsSync(permissionsPath)) {
    const defaultPerms = {
      allow_shell: true,
      allow_write: true,
      allow_read: true,
      deny_commands: ['rm -rf /', 'shutdown', 'reboot', 'format'],
      deny_paths: ['.git/objects', '.env', '.roland-permissions.json'],
      extra_instructions: '',
    };
    fs.writeFileSync(permissionsPath, JSON.stringify(defaultPerms, null, 2), 'utf-8');
    console.log(`   ✅ Created .roland-permissions.json`);
  } else {
    console.log(`   ⏭️  .roland-permissions.json already exists — skipping`);
  }

  // ── Step 7: Scaffold .roland/ directory + project-context.json ───────────
  const rolandDir = path.join(targetDir, '.roland');
  if (!fs.existsSync(rolandDir)) {
    fs.mkdirSync(rolandDir, { recursive: true });
  }
  const projectContextPath = path.join(rolandDir, 'project-context.json');
  if (!fs.existsSync(projectContextPath)) {
    const defaultContext = {
      version: '1.0',
      project: {
        name: path.basename(targetDir),
      },
      conventions: [],
      patterns: [],
      decisions: [],
      errors: [],
      last_updated: new Date().toISOString(),
    };
    fs.writeFileSync(projectContextPath, JSON.stringify(defaultContext, null, 2), 'utf-8');
    console.log(`   ✅ Created .roland/project-context.json`);
  } else {
    console.log(`   ⏭️  .roland/project-context.json already exists — skipping`);
  }

  const modelQualityPath = path.join(rolandDir, 'model-quality.json');
  if (!fs.existsSync(modelQualityPath)) {
    fs.writeFileSync(modelQualityPath, '[]', 'utf-8');
    console.log(`   ✅ Created .roland/model-quality.json`);
  } else {
    console.log(`   ⏭️  .roland/model-quality.json already exists — skipping`);
  }

  console.log(`   💡 Consider adding .roland/ to your .gitignore`);

  console.log(`\n🎉 Roland is ready in ${targetDir}`);
  console.log(`\nNext steps:`);
  console.log(`  1. Open ${targetDir} in Cursor or VS Code`);
  console.log(`  2. Verify MCP server: Settings → MCP (Cursor) or MCP: List Servers (VS Code)`);
  console.log(`  3. In chat, try: "Use the health_check tool"`);
  console.log(`  4. Edit roland-context.json to add your VB6→C# mapping rules`);
  console.log(`     or use: update_migration_context type=rule pattern=... replacement=...`);
  console.log(`  5. Start a Goose session — context loads automatically via .goose/config.yaml`);
}

main();
