#!/usr/bin/env node
/**
 * Roland PR cleanup — retroactively rename legacy autogenerated PR titles and bodies.
 *
 * Usage:
 *   roland pr-cleanup                    # scan up to 20 open PRs (dry-run)
 *   roland pr-cleanup --apply            # perform edits via `gh pr edit`
 *   roland pr-cleanup --current          # format PR on current branch only
 *   roland pr-cleanup --current --apply  # apply to current branch PR
 *   roland pr-cleanup --body --apply     # also migrate legacy "## Roland Run" bodies
 *   roland pr-cleanup --limit 10         # scan fewer PRs
 *   node scripts/pr-cleanup.ts --apply   # standalone script (requires build or tsx)
 */

import {
  cleanupLegacyPrTitles,
  formatCurrentPr,
  formatPrFromGoal,
  suggestPrCleanup,
} from './pr-format.js';

const c = {
  bold: (s: string) => `\x1b[1m${s}\x1b[0m`,
  dim: (s: string) => `\x1b[2m${s}\x1b[0m`,
  green: (s: string) => `\x1b[32m${s}\x1b[0m`,
  yellow: (s: string) => `\x1b[33m${s}\x1b[0m`,
  red: (s: string) => `\x1b[31m${s}\x1b[0m`,
  cyan: (s: string) => `\x1b[36m${s}\x1b[0m`,
};

function err(s = ''): void {
  process.stderr.write(s + '\n');
}

export interface PrCleanupCliArgs {
  apply: boolean;
  limit: number;
  current: boolean;
  updateBody: boolean;
  /** Preview format from a goal string (no gh required). */
  previewGoal?: string;
  prNumber?: number;
}

export function parsePrCleanupArgs(argv: string[]): PrCleanupCliArgs {
  const args = argv[0] === 'pr-cleanup' ? argv.slice(1) : argv;
  let apply = false;
  let limit = 20;
  let current = false;
  let updateBody = false;
  let previewGoal: string | undefined;
  let prNumber: number | undefined;

  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === '--apply') { apply = true; continue; }
    if (a === '--current' || a === '-c') { current = true; continue; }
    if (a === '--body' || a === '--update-body') { updateBody = true; continue; }
    if ((a === '--limit' || a === '-n') && args[i + 1]) {
      limit = Math.max(1, Number(args[++i]) || 20);
      continue;
    }
    if ((a === '--goal' || a === '-g') && args[i + 1]) {
      previewGoal = args[++i];
      continue;
    }
    if ((a === '--pr' || a === '-p') && args[i + 1]) {
      prNumber = Number(args[++i]) || undefined;
      continue;
    }
  }

  return { apply, limit, current, updateBody, previewGoal, prNumber };
}

function printPreviewGoal(goal: string): void {
  const formatted = formatPrFromGoal(goal, { runId: 'preview' });
  err('');
  err(`  ${c.bold('PR preview')}  ${c.dim('(from goal — no gh required)')}`);
  err('');
  err(`  ${c.cyan('Title:')}`);
  err(`    ${formatted.title}`);
  err('');
  err(`  ${c.cyan('Body:')}`);
  for (const line of formatted.body.split('\n')) {
    err(`    ${line}`);
  }
  err('');
}

function printResult(
  result: ReturnType<typeof cleanupLegacyPrTitles>,
  dryRun: boolean,
  mode: string,
): void {
  if (result.errors.length > 0) {
    for (const e of result.errors) {
      err(`  ${c.red('✗')} ${e}`);
    }
    err('');
  }

  if (result.items.length === 0) {
    err(`  ${c.dim('No legacy PR titles found' + (mode === 'batch' ? ' in the scanned set' : '') + '.')}`);
    err(`  ${c.dim('Convention:')} feat(scope): short description — see docs/guides/pr-title-convention.md`);
    err('');
    process.exit(result.errors.length > 0 ? 1 : 0);
  }

  for (const item of result.items) {
    err(`  ${c.yellow('PR #' + item.number)}${item.bodyUpdated ? c.dim(' (+ body)') : ''}`);
    err(`    ${c.dim('was:')} ${item.oldTitle}`);
    err(`    ${c.green('now:')} ${item.newTitle}`);
  }

  err('');
  err(
    `  Scanned ${result.scanned} · `
    + `${dryRun ? 'would update' : 'updated'} ${result.updated} · `
    + `skipped ${result.skipped}`,
  );
  err('');

  if (dryRun && result.updated > 0) {
    err(`  Run ${c.bold('roland pr-cleanup --apply')} to apply these changes.`);
    if (!result.items.some((i) => i.bodyUpdated)) {
      err(`  Add ${c.bold('--body')} to also migrate legacy "## Roland Run" descriptions.`);
    }
    err('');
  }
}

export function runPrCleanupCli(argv: string[]): void {
  const { apply, limit, current, updateBody, previewGoal, prNumber } = parsePrCleanupArgs(argv);

  if (previewGoal) {
    printPreviewGoal(previewGoal);
    process.exit(0);
  }

  const cwd = process.env.ROLAND_PROJECT_ROOT?.trim() || process.cwd();
  const dryRun = !apply;

  err('');
  err(
    `  ${c.bold('PR title cleanup')}  `
    + `${c.dim(dryRun ? '(dry-run — pass --apply to edit)' : '(applying changes)')}`,
  );
  err(`  ${c.dim('Repo:')}  ${cwd}`);
  if (current) {
    err(`  ${c.dim('Mode:')} current branch PR`);
  } else if (prNumber) {
    err(`  ${c.dim('Mode:')} PR #${prNumber}`);
  } else {
    err(`  ${c.dim('Limit:')} ${limit} open PRs`);
  }
  if (updateBody) {
    err(`  ${c.dim('Body:')}  migrate legacy descriptions`);
  }
  err('');

  const result = current
    ? formatCurrentPr(cwd, { dryRun, updateBody })
    : cleanupLegacyPrTitles(cwd, { limit, dryRun, updateBody, prNumber });

  printResult(result, dryRun, current ? 'current' : 'batch');
  process.exit(result.errors.length > 0 ? 1 : 0);
}

/** Suggest cleanup for arbitrary title/body (used by agents and tests). */
export function previewPrCleanup(title: string, body?: string): ReturnType<typeof suggestPrCleanup> {
  return suggestPrCleanup(title, body);
}
