#!/usr/bin/env node
/**
 * Roland PR cleanup — retroactively rename legacy autogenerated PR titles.
 *
 * Usage:
 *   roland pr-cleanup              # rename up to 20 open PRs (dry-run)
 *   roland pr-cleanup --apply      # perform edits via `gh pr edit`
 *   roland pr-cleanup --limit 10   # scan fewer PRs
 */

import { cleanupLegacyPrTitles } from './pr-format.js';

const c = {
  bold: (s: string) => `\x1b[1m${s}\x1b[0m`,
  dim: (s: string) => `\x1b[2m${s}\x1b[0m`,
  green: (s: string) => `\x1b[32m${s}\x1b[0m`,
  yellow: (s: string) => `\x1b[33m${s}\x1b[0m`,
  red: (s: string) => `\x1b[31m${s}\x1b[0m`,
};

function err(s = ''): void {
  process.stderr.write(s + '\n');
}

export interface PrCleanupCliArgs {
  apply: boolean;
  limit: number;
}

export function parsePrCleanupArgs(argv: string[]): PrCleanupCliArgs {
  const args = argv[0] === 'pr-cleanup' ? argv.slice(1) : argv;
  let apply = false;
  let limit = 20;

  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === '--apply') { apply = true; continue; }
    if ((a === '--limit' || a === '-n') && args[i + 1]) {
      limit = Math.max(1, Number(args[++i]) || 20);
      continue;
    }
  }

  return { apply, limit };
}

export function runPrCleanupCli(argv: string[]): void {
  const { apply, limit } = parsePrCleanupArgs(argv);
  const cwd = process.env.ROLAND_PROJECT_ROOT?.trim() || process.cwd();
  const dryRun = !apply;

  err('');
  err(`  ${c.bold('PR title cleanup')}  ${c.dim(dryRun ? '(dry-run — pass --apply to edit)' : '(applying changes)')}`);
  err(`  ${c.dim('Repo:')}  ${cwd}`);
  err(`  ${c.dim('Limit:')} ${limit} open PRs`);
  err('');

  const result = cleanupLegacyPrTitles(cwd, { limit, dryRun });

  if (result.errors.length > 0) {
    for (const e of result.errors) {
      err(`  ${c.red('✗')} ${e}`);
    }
    err('');
  }

  if (result.items.length === 0) {
    err(`  ${c.dim('No legacy PR titles found in the scanned set.')}`);
    err(`  ${c.dim('Convention:')} feat(scope): short description — see docs/guides/pr-title-convention.md`);
    err('');
    process.exit(result.errors.length > 0 ? 1 : 0);
  }

  for (const item of result.items) {
    err(`  ${c.yellow('PR #' + item.number)}`);
    err(`    ${c.dim('was:')} ${item.oldTitle}`);
    err(`    ${c.green('now:')} ${item.newTitle}`);
  }

  err('');
  err(
    `  Scanned ${result.scanned} · `
    + `${dryRun ? 'would update' : 'updated'} ${result.updated} · `
    + `skipped ${result.skipped}`,
  );
  err('');

  if (dryRun && result.updated > 0) {
    err(`  Run ${c.bold('roland pr-cleanup --apply')} to apply these title changes.`);
    err('');
  }

  process.exit(result.errors.length > 0 ? 1 : 0);
}
