/**
 * PR title & description formatting for Roland task git workflow.
 *
 * Produces conventional-commit style titles (feat/fix/refactor/…) and structured
 * PR bodies without redundant mission prefixes like "Task task-1:" or "[Mission: …]".
 */

import fs from 'fs';
import os from 'os';
import path from 'path';
import { execSync, spawnSync } from 'child_process';

/** Conventional-commit types Roland may emit for autogenerated PRs. */
export type ConventionalCommitType = 'feat' | 'fix' | 'refactor' | 'docs' | 'test' | 'chore';

export interface PrFormatTaskInput {
  id: string;
  title: string;
  agent: string;
  description?: string;
}

export interface PrFormatContext {
  goal: string;
  runId: string;
  missionUrl?: string;
  /** Optional Vanguard / test-executor summary for the Testing section. */
  testingNotes?: string;
  /** Optional one-liner for the Impact section (why this change matters). */
  impactNote?: string;
}

/** Title + body pair returned by formatters. */
export interface FormattedPr {
  title: string;
  body: string;
}

export interface PrCleanupSuggestion {
  title: string;
  body: string | null;
  titleChanged: boolean;
  bodyChanged: boolean;
}

export interface PrCleanupItem {
  number: number;
  oldTitle: string;
  newTitle: string;
  bodyUpdated?: boolean;
}

export interface PrCleanupResult {
  scanned: number;
  updated: number;
  skipped: number;
  dryRun: boolean;
  items: PrCleanupItem[];
  errors: string[];
}

const MAX_PR_TITLE_LEN = 72;

const TYPE_RULES: Array<{ type: ConventionalCommitType; pattern: RegExp }> = [
  { type: 'fix', pattern: /\b(fix|bug|hotfix|patch|resolve|repair|crash|error|broken|regression)\b/i },
  { type: 'refactor', pattern: /\b(refactor|restructure|reorganiz|rename|clean up|extract|simplif)\b/i },
  { type: 'docs', pattern: /\b(document|documentation|readme|guide|comment|spec)\b/i },
  { type: 'test', pattern: /\b(test|coverage|e2e|vitest|jest|regression test|characterization)\b/i },
  { type: 'chore', pattern: /\b(chore|deps|dependency|bump|ci\b|config|tooling|lint)\b/i },
];

const SCOPE_RULES: Array<{ scope: string; pattern: RegExp }> = [
  { scope: 'dashboard', pattern: /\b(dashboard|mobile|responsive|layout|ui|tailwind)\b/i },
  { scope: 'git', pattern: /\b(github|git\b|branch|pull request|\bpr\b|commit)\b/i },
  { scope: 'loop', pattern: /\b(loop[- ]?engine|critique|retry|verification|escalat)\b/i },
  { scope: 'pm', pattern: /\b(pm\b|team|orchestrat|mission|blackboard)\b/i },
  { scope: 'mcp', pattern: /\b(mcp\b|cursor|agent)\b/i },
  { scope: 'api', pattern: /\b(api\b|endpoint|route|middleware|express)\b/i },
  { scope: 'auth', pattern: /\b(auth|login|token|jwt|session)\b/i },
];

const LEGACY_TITLE_PATTERNS = [
  /^Task\s+task[-_]/i,
  /^Roland:\s/i,
  /^\[Mission:/i,
  /^Task[-_]\d+:/i,
];

/** Minimum chars after cleaning before we accept the result (else fallback). */
const MIN_USEFUL_PR_CHARS = 16;

/** Max summary length (chars) for one- or two-sentence overviews. */
const MAX_SUMMARY_CHARS = 320;

/**
 * Section-start patterns — entire blocks from match until the next section boundary are removed.
 * Covers PM mandates, agent handoff output, and legacy Roland templates.
 */
const NOISE_SECTION_PATTERNS: RegExp[] = [
  /⚠️\s*PRODUCTION HARDENING[\s\S]*?(?=\n(?:#{1,3}\s|\*\*[A-Z][^*\n]+?\*\*|\Z))/gi,
  /⚠️\s*\.NET TEST CONVENTIONS[\s\S]*?(?=\n(?:#{1,3}\s|\*\*[A-Z][^*\n]+?\*\*|\Z))/gi,
  /#{1,6}\s*Sparrow Handoff Protocol[\s\S]*?(?=\n#{1,3}\s|\n\*\*[A-Z][^*\n]+?\*\*|\Z)/gi,
  /#{1,6}\s*Sparrow\s*[—–-]\s*Task Complete[\s\S]*?(?=\n#{1,6}\s|\Z)/gi,
  /#{1,6}\s*Assumptions\b[\s\S]*?(?=\n#{1,3}\s|\n\*\*[A-Z][^*\n]+?\*\*|\Z)/gi,
  /#{1,6}\s*Roland Run\b[\s\S]*?(?=\n#{1,3}\s|\n\*\*[A-Z][^*\n]+?\*\*|\Z)/gi,
  /#{1,6}\s*HARD RULE[\s\S]*?(?=\n#{1,3}\s|\n\*\*[A-Z][^*\n]+?\*\*|\Z)/gi,
  /#{1,6}\s*Production Hardening Mandate[\s\S]*?(?=\n#{1,3}\s|\n\*\*[A-Z][^*\n]+?\*\*|\Z)/gi,
  /#{1,6}\s*Blackboard Hygiene[\s\S]*?(?=\n#{1,3}\s|\n\*\*[A-Z][^*\n]+?\*\*|\Z)/gi,
  /```[\s\S]*?```/g,
];

/** Line-level noise — drop individual lines that match (PM checklists, .NET mandates, agent boilerplate). */
const NOISE_LINE_PATTERNS: RegExp[] = [
  /^\s*[-*]\s*\[[ xX]\]/,
  /^\s*\*\*pmNotes:\*\*/i,
  /^\s*pmNotes:/i,
  /Generated automatically by Roland/i,
  /^\s*\*Draft PR opened by Roland/i,
  /^\s*Closes task task-/i,
  /^\s*Generated by Roland\s*$/i,
  /\bEF Core migrations?\b/i,
  /\bFluentValidation\b/i,
  /\bRFC 7807 ProblemDetails\b/i,
  /\bProblemDetails with (appropriate )?status/i,
  /\bCancellationToken\b/i,
  /\bILogger<T>\b/i,
  /\bWebApplicationFactory\b/i,
  /\bASP\.NET Core RateLimiter\b/i,
  /\bNSubstitute\b|\bMoq\b/,
  /\bSparrow Handoff Protocol\b/i,
  /\bSparrow quality bar\b/i,
  /\bProduction Hardening Mandate\b/i,
  /\bExplicitly state which items do NOT apply\b/i,
  /^\s*Task task[-_]?\d+:/i,
  /^\s*\[Mission:/i,
  /^\s*Team Goal:/i,
  /^\s*Roland:\s/i,
  /^\s*⚠️\s/,
  /^\s*---\s*$/,
  /^\s*#{1,6}\s*Roland Run\b/i,
  /^\s*#{1,6}\s*Sparrow\b/i,
  /^\s*#{1,6}\s*Assumptions\b/i,
  /^\s*#{1,6}\s*HARD RULE/i,
  /^\s*\*\*Objective:\*\*/i,
  /^\s*\*\*Changes:\*\*/i,
  /^\s*\*\*Wiring:\*\*/i,
  /^\s*\*\*Defensive:\*\*/i,
  /^\s*\*\*Verification:\*\*/i,
  /^\s*\*\*Follow-up:\*\*/i,
  /^\s*\*\*TODOs left:\*\*/i,
  /^\s*#{1,6}\s*Impact\b/i,
  /^\s*#{1,6}\s*Summary\b/i,
  /^\s*#{1,6}\s*Key changes?\b/i,
  /^\s*#{1,6}\s*Testing\b/i,
  /^\s*#{1,6}\s*Related\b/i,
  /^\s*\*\*Summary\*\*\s*$/i,
  /^\s*\*\*Key Changes?\*\*\s*$/i,
  /^\s*\*\*Testing\*\*\s*$/i,
  /^\s*\*\*Related\*\*\s*$/i,
  /^\s*\*\*Goal:\*\*/i,
  /^\s*\*\*Task:\*\*/i,
  /^\s*\*\*Run:\*\*/i,
  /^\s*\*\*Mission:\*\*/i,
  /^\s*\*\*Dashboard:\*\*/i,
  /^\s*-\s*\*\*Task:\*\*/i,
  /^\s*-\s*\*\*Run:\*\*/i,
  /^\s*-\s*\*\*Mission:\*\*/i,
  /^\s*-\s*\*\*Dashboard:\*\*/i,
  /^\s*-\s*Roland PM team workflow/i,
  /^\s*-\s*Manual review recommended/i,
];

/** Signals that raw text is agent/PM boilerplate unsuitable for a PR body. */
const NOISY_CONTENT_SIGNALS: RegExp[] = [
  /⚠️\s*PRODUCTION HARDENING/i,
  /#{1,6}\s*Sparrow\s*[—–-]\s*Task Complete/i,
  /\bEF Core migrations?\b/i,
  /\bFluentValidation or DataAnnotations\b/i,
  /#{1,6}\s*Sparrow Handoff Protocol/i,
  /Task task-\d+:/i,
  /\[Mission:/i,
  /#{1,6}\s*Assumptions\b/i,
  /Explicitly state which items do NOT apply/i,
  /#{1,6}\s*Roland Run\b/i,
  /Generated automatically by Roland/i,
];

function collapseBlankLines(text: string): string {
  return text.replace(/\n{3,}/g, '\n\n').trim();
}

function removeNoiseSections(text: string): string {
  let result = text;
  for (const pattern of NOISE_SECTION_PATTERNS) {
    result = result.replace(pattern, '\n');
  }
  return result;
}

function filterNoiseLines(text: string): string {
  return text
    .split('\n')
    .filter((line) => {
      const trimmed = line.trim();
      if (!trimmed) return true;
      return !NOISE_LINE_PATTERNS.some((re) => re.test(trimmed));
    })
    .join('\n');
}

/** Strip mission/task boilerplate from free text. */
export function stripMissionNoise(text: string): string {
  if (!text?.trim()) return '';
  return text
    .replace(/^\[P\d+\s+active\]\s*/i, '')
    .replace(/\[Mission:\s*[^\]]+\]\s*/gi, '')
    .replace(/\[Mission:\s*[^\]]+\]\s*Team\s+Goal:\s*/gi, '')
    .replace(/Team\s+Goal:\s*/gi, '')
    .replace(/^Task\s+task[-_]?\d+:\s*/i, '')
    .replace(/^Task[-_]?\d+:\s*/i, '')
    .replace(/^Roland:\s*/i, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Extract a short one- or two-sentence summary from noisy mission/task text.
 * Used when aggressive cleaning would otherwise leave too little content.
 */
export function extractShortSummary(text: string, maxChars = MAX_SUMMARY_CHARS): string {
  const stripped = stripMissionNoise(text);
  const seed = stripped || text.replace(/\s+/g, ' ').trim();
  if (!seed) return '';

  const sentences = seed
    .split(/(?<=[.!?])\s+/)
    .map((s) => s.trim())
    .filter((s) => {
      if (s.length <= 8) return false;
      if (NOISE_LINE_PATTERNS.some((re) => re.test(s))) return false;
      if (isNoisyPrContent(s)) return false;
      return true;
    });

  if (sentences.length === 0) {
    const firstLine = seed.split(/\n/).map((l) => l.trim()).find(Boolean) ?? seed;
    return firstLine.slice(0, maxChars).trim();
  }

  let summary = sentences[0];
  if (sentences.length > 1 && summary.length < maxChars * 0.6) {
    const combined = `${summary} ${sentences[1]}`;
    summary = combined.length <= maxChars ? combined : summary;
  }
  return summary.slice(0, maxChars).trim();
}

/**
 * Aggressively remove PM mandates, Sparrow agent output, .NET hardening checklists,
 * and legacy Roland templates from raw PR text.
 *
 * Falls back to {@link extractShortSummary} when cleaning removes too much useful content.
 */
export function cleanPrDescription(rawText: string): string {
  if (!rawText?.trim()) return '';

  const original = rawText.trim();
  let cleaned = collapseBlankLines(filterNoiseLines(removeNoiseSections(original)));

  // Flatten overly long single paragraphs that survived section removal.
  const lines = cleaned
    .split('\n')
    .map((l) => stripMissionNoise(l.trim()))
    .filter(Boolean);

  cleaned = collapseBlankLines(lines.join('\n'));

  if (cleaned.length >= MIN_USEFUL_PR_CHARS) {
    return cleaned;
  }

  const fallback = extractShortSummary(original);
  if (fallback.length >= MIN_USEFUL_PR_CHARS && !isNoisyPrContent(fallback)) {
    return fallback;
  }

  return 'Implements the scoped deliverable for this change.';
}

/** True when text contains PM/agent boilerplate that should not appear in a PR body. */
export function isNoisyPrContent(text: string): boolean {
  const t = text?.trim() ?? '';
  if (!t) return false;
  return NOISY_CONTENT_SIGNALS.some((re) => re.test(t));
}

/** Infer conventional-commit type from task wording. */
export function inferCommitType(title: string, description?: string): ConventionalCommitType {
  const haystack = `${title} ${description ?? ''}`;
  for (const rule of TYPE_RULES) {
    if (rule.pattern.test(haystack)) return rule.type;
  }
  return 'feat';
}

/** Infer a short scope token from task wording. */
export function inferScope(title: string, description?: string): string {
  const haystack = `${title} ${description ?? ''}`;
  for (const rule of SCOPE_RULES) {
    if (rule.pattern.test(haystack)) return rule.scope;
  }
  return 'roland';
}

/** Lowercase imperative subject for conventional commits (no trailing period). */
export function formatCommitSubject(text: string): string {
  const clean = stripMissionNoise(text);
  if (!clean) return 'update roland task output';
  const lowered = clean.charAt(0).toLowerCase() + clean.slice(1);
  return lowered.replace(/[.!?]+$/, '').trim();
}

function truncateTitle(type: string, scope: string, subject: string): string {
  const prefix = `${type}(${scope}): `;
  const maxSubject = MAX_PR_TITLE_LEN - prefix.length;
  if (maxSubject < 8) return `${type}(${scope}): update`.slice(0, MAX_PR_TITLE_LEN);
  const trimmed = subject.length > maxSubject
    ? subject.slice(0, maxSubject - 1).trimEnd() + '…'
    : subject;
  return `${prefix}${trimmed}`;
}

/** Build a conventional-commit PR title from task metadata. */
export function buildConventionalPrTitle(task: PrFormatTaskInput): string {
  const cleanTitle = stripMissionNoise(task.title);
  const subject = formatCommitSubject(cleanTitle || task.title);
  const type = inferCommitType(cleanTitle || task.title, task.description);
  const scope = inferScope(cleanTitle || task.title, task.description);
  return truncateTitle(type, scope, subject);
}

/** True when a PR title uses legacy Roland/mission prefixes. */
export function isLegacyPrTitle(title: string): boolean {
  const t = title?.trim() ?? '';
  if (!t) return false;
  return LEGACY_TITLE_PATTERNS.some((re) => re.test(t));
}

/**
 * Derive a clean conventional title from a legacy PR title (and optional body).
 * Returns null when the title is already clean or cannot be migrated.
 */
export function migrateLegacyPrTitle(title: string, body?: string): string | null {
  const trimmed = title?.trim() ?? '';
  if (!trimmed || !isLegacyPrTitle(trimmed)) return null;

  let seed = stripMissionNoise(trimmed);
  if (!seed && body) {
    const goalMatch = body.match(/\*\*Goal:\*\*\s*(.+)/i)
      ?? body.match(/## Mission Goal\s*\n+(.+)/i)
      ?? body.match(/\*\*Title:\*\*\s*(.+)/i);
    seed = goalMatch ? stripMissionNoise(goalMatch[1]) : '';
  }
  if (!seed) return null;

  return buildConventionalPrTitle({
    id: 'legacy',
    title: seed,
    agent: 'executor',
    description: body,
  });
}

function bulletizeDescription(description: string): string[] {
  const cleaned = cleanPrDescription(description);
  const lines = cleaned
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .map((l) => l.replace(/^[-*]\s+/, '').trim())
    .filter((l) => l.length > 4 && !NOISE_LINE_PATTERNS.some((re) => re.test(l)));

  if (lines.length === 0) {
    const summary = extractShortSummary(description);
    return summary ? [`- ${summary}`] : ['- Task deliverable as described in the mission plan.'];
  }
  if (lines.length === 1) return [`- ${lines[0]}`];
  return lines.slice(0, 6).map((l) => (l.startsWith('- ') ? l : `- ${l}`));
}

/** Structured markdown PR body for Roland executor tasks. */
export function buildPrDescription(task: PrFormatTaskInput, ctx: PrFormatContext): string {
  const rawDesc = task.description?.trim() || task.title;
  const summarySource =
    extractShortSummary(rawDesc)
    || extractShortSummary(task.title)
    || cleanPrDescription(rawDesc);
  const mission = stripMissionNoise(ctx.goal) || '';
  const keyChanges = bulletizeDescription(rawDesc);

  const testing = ctx.testingNotes?.trim()
    ? ctx.testingNotes.trim().split('\n').map((l) => {
      const t = l.trim();
      return t.startsWith('- ') ? t : `- ${t}`;
    }).join('\n')
    : '- Roland PM team workflow (executor task completion + automated git push)\n'
    + '- Manual review recommended before marking PR ready for merge';

  const lines = [
    '**Summary**',
    summarySource || 'Implements the scoped Roland team task deliverable.',
    '',
    '**Key Changes**',
    ...keyChanges,
    '',
    '**Testing**',
    testing,
    '',
    '**Related**',
    `- Task \`${task.id}\` (${task.agent})`,
  ];

  if (mission) {
    lines.push(`- Mission: ${mission}`);
  }
  lines.push(`- Run \`${ctx.runId}\``);

  if (ctx.missionUrl) {
    lines.push(`- Dashboard: ${ctx.missionUrl}`);
  }

  if (ctx.impactNote?.trim()) {
    lines.push('', '**Impact**', ctx.impactNote.trim());
  }

  return lines.join('\n');
}

/**
 * Build a clean conventional title + structured body from a mission goal.
 * Used by roland-web and manual PR creation paths outside task-git-workflow.
 */
export function formatPrFromGoal(
  goal: string,
  opts?: {
    runId?: string;
    testingNotes?: string;
    impactNote?: string;
    missionUrl?: string;
    agent?: string;
    taskId?: string;
  },
): FormattedPr {
  const cleanGoal = stripMissionNoise(goal) || goal.trim();
  const summary = extractShortSummary(goal) || cleanGoal;
  const task: PrFormatTaskInput = {
    id: opts?.taskId ?? 'mission',
    title: summary,
    agent: opts?.agent ?? 'executor',
    description: summary,
  };
  const ctx: PrFormatContext = {
    goal: cleanGoal,
    runId: opts?.runId ?? 'roland-run',
    testingNotes: opts?.testingNotes,
    impactNote: opts?.impactNote,
    missionUrl: opts?.missionUrl,
  };
  return {
    title: buildConventionalPrTitle(task),
    body: buildPrDescription(task, ctx),
  };
}

/** True when a PR body uses legacy templates or contains PM/agent boilerplate. */
export function isLegacyPrBody(body: string): boolean {
  const b = body?.trim() ?? '';
  if (!b) return false;
  if (isNoisyPrContent(b)) return true;
  if (b.includes('**Summary**') && b.includes('**Key Changes**')) return false;
  if (b.includes('## Summary') && b.includes('## Key changes')) return false;
  return /^## Roland Run\b/im.test(b)
    || /^\*\*Goal:\*\*\s/m.test(b)
    || /Generated automatically by Roland/i.test(b);
}

/**
 * Rebuild a structured PR body from a legacy "## Roland Run" template.
 */
export function migrateLegacyPrBody(
  title: string,
  body: string,
  ctx?: Partial<PrFormatContext>,
): string {
  const goalMatch = body.match(/\*\*Goal:\*\*\s*(.+)/i)
    ?? body.match(/## Mission Goal\s*\n+(.+)/i);
  const rawSeed = goalMatch ? goalMatch[1] : title;
  const seed = extractShortSummary(rawSeed) || stripMissionNoise(rawSeed) || stripMissionNoise(title);
  const task: PrFormatTaskInput = {
    id: ctx?.runId ?? 'legacy',
    title: seed || title,
    agent: 'executor',
    description: seed || cleanPrDescription(body) || title,
  };
  return buildPrDescription(task, {
    goal: seed || stripMissionNoise(title),
    runId: ctx?.runId ?? 'legacy-cleanup',
    missionUrl: ctx?.missionUrl,
    testingNotes: ctx?.testingNotes,
    impactNote: ctx?.impactNote,
  });
}

/** Rebuild a clean structured body from any noisy raw PR text. */
export function rebuildPrBodyFromNoise(
  title: string,
  rawBody: string,
  ctx?: Partial<PrFormatContext>,
): string {
  const seed = extractShortSummary(rawBody)
    || extractShortSummary(title)
    || stripMissionNoise(title);
  const cleaned = cleanPrDescription(rawBody);
  const task: PrFormatTaskInput = {
    id: ctx?.runId ?? 'cleanup',
    title: seed || title,
    agent: 'executor',
    description: cleaned || seed || title,
  };
  return buildPrDescription(task, {
    goal: seed || stripMissionNoise(title),
    runId: ctx?.runId ?? 'cleanup',
    missionUrl: ctx?.missionUrl,
    testingNotes: ctx?.testingNotes,
    impactNote: ctx?.impactNote,
  });
}

/** Suggest clean title and body for an existing PR without mutating GitHub. */
export function suggestPrCleanup(title: string, body?: string): PrCleanupSuggestion {
  const trimmedTitle = title?.trim() ?? '';
  const trimmedBody = body?.trim() ?? '';

  let newTitle = trimmedTitle;
  let titleChanged = false;
  if (isLegacyPrTitle(trimmedTitle)) {
    const migrated = migrateLegacyPrTitle(trimmedTitle, trimmedBody);
    if (migrated && migrated !== trimmedTitle) {
      newTitle = migrated;
      titleChanged = true;
    }
  }

  let newBody: string | null = null;
  let bodyChanged = false;
  const needsBodyCleanup = trimmedBody && (
    isLegacyPrBody(trimmedBody)
    || isNoisyPrContent(trimmedBody)
  );
  if (needsBodyCleanup) {
    newBody = isLegacyPrBody(trimmedBody) && /^## Roland Run\b/im.test(trimmedBody)
      ? migrateLegacyPrBody(newTitle, trimmedBody)
      : rebuildPrBodyFromNoise(newTitle, trimmedBody);
    bodyChanged = newBody !== trimmedBody;
  }

  return { title: newTitle, body: newBody, titleChanged, bodyChanged };
}

/** Conventional commit message body for per-task git commits. */
export function buildTaskCommitMessage(task: PrFormatTaskInput): string {
  const title = buildConventionalPrTitle(task);
  return [
    title,
    '',
    `Closes task ${task.id}`,
    '',
    'Generated by Roland',
  ].join('\n');
}

function ghAvailable(): boolean {
  try {
    const r = spawnSync('gh', ['--version'], { stdio: 'ignore' });
    return r.status === 0;
  } catch {
    return false;
  }
}

/** Fetch the open PR for the current git branch via `gh`, if any. */
export function getCurrentPrFromGh(cwd: string): { number: number; title: string; body: string } | null {
  if (!ghAvailable()) return null;
  try {
    const json = execSync(
      'gh pr view --json number,title,body',
      { cwd, encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] },
    );
    const row = JSON.parse(json) as { number?: number; title?: string; body?: string };
    if (!row.number || !row.title) return null;
    return { number: row.number, title: row.title, body: row.body ?? '' };
  } catch {
    return null;
  }
}

/**
 * Format (or preview formatting for) the PR on the current branch.
 * Updates title and/or body when legacy patterns are detected.
 */
export function formatCurrentPr(
  cwd: string,
  opts?: { dryRun?: boolean; updateBody?: boolean },
): PrCleanupResult {
  const dryRun = opts?.dryRun ?? false;
  const updateBody = opts?.updateBody ?? true;
  const result: PrCleanupResult = {
    scanned: 0,
    updated: 0,
    skipped: 0,
    dryRun,
    items: [],
    errors: [],
  };

  if (!ghAvailable()) {
    result.errors.push('`gh` CLI not found — install from https://cli.github.com/');
    return result;
  }

  const row = getCurrentPrFromGh(cwd);
  if (!row) {
    result.errors.push('No open PR found for the current branch — create one or pass a PR number');
    return result;
  }

  result.scanned = 1;
  return applyPrCleanupSuggestion(cwd, row, { dryRun, updateBody, result });
}

function applyPrCleanupSuggestion(
  cwd: string,
  row: { number: number; title: string; body: string },
  opts: { dryRun: boolean; updateBody: boolean; result: PrCleanupResult },
): PrCleanupResult {
  const { dryRun, updateBody, result } = opts;
  const suggestion = suggestPrCleanup(row.title, row.body);

  if (!suggestion.titleChanged && !(updateBody && suggestion.bodyChanged)) {
    result.skipped++;
    return result;
  }

  result.items.push({
    number: row.number,
    oldTitle: row.title,
    newTitle: suggestion.title,
    bodyUpdated: updateBody && suggestion.bodyChanged,
  });

  if (dryRun) {
    result.updated++;
    return result;
  }

  try {
    const args = ['pr', 'edit', String(row.number), '--title', suggestion.title];
    if (updateBody && suggestion.body) {
      const bodyFile = path.join(os.tmpdir(), `roland-pr-body-${row.number}-${Date.now()}.md`);
      fs.writeFileSync(bodyFile, suggestion.body, 'utf-8');
      try {
        execSync(
          `gh pr edit ${row.number} --title ${JSON.stringify(suggestion.title)} --body-file ${JSON.stringify(bodyFile)}`,
          { cwd, encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] },
        );
      } finally {
        try { fs.unlinkSync(bodyFile); } catch { /* ignore */ }
      }
    } else {
      execSync(
        `gh pr edit ${row.number} --title ${JSON.stringify(suggestion.title)}`,
        { cwd, encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] },
      );
    }
    result.updated++;
  } catch (e) {
    result.errors.push(
      `PR #${row.number}: ${e instanceof Error ? e.message : String(e)}`,
    );
  }

  return result;
}

/**
 * Best-effort batch rename of recent open PRs with legacy titles via `gh pr edit`.
 * Safe to run with --dry-run; skips PRs that already match the convention.
 */
export function cleanupLegacyPrTitles(
  cwd: string,
  opts?: { limit?: number; dryRun?: boolean; updateBody?: boolean; prNumber?: number },
): PrCleanupResult {
  const limit = Math.max(1, Math.min(opts?.limit ?? 20, 100));
  const dryRun = opts?.dryRun ?? false;
  const result: PrCleanupResult = {
    scanned: 0,
    updated: 0,
    skipped: 0,
    dryRun,
    items: [],
    errors: [],
  };

  if (!ghAvailable()) {
    result.errors.push('`gh` CLI not found — install from https://cli.github.com/');
    return result;
  }

  let rows: Array<{ number: number; title: string; body: string }>;
  try {
    const json = execSync(
      `gh pr list --state open --limit ${limit} --json number,title,body`,
      { cwd, encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] },
    );
    rows = JSON.parse(json) as Array<{ number: number; title: string; body: string }>;
  } catch (e) {
    result.errors.push(e instanceof Error ? e.message : String(e));
    return result;
  }

  const updateBody = opts?.updateBody ?? false;

  if (opts?.prNumber) {
    const match = rows.find((r) => r.number === opts.prNumber);
    if (!match) {
      result.errors.push(`PR #${opts.prNumber} not found among open PRs (limit ${limit})`);
      return result;
    }
    result.scanned = 1;
    return applyPrCleanupSuggestion(cwd, match, { dryRun, updateBody, result });
  }

  for (const row of rows) {
    result.scanned++;
    const suggestion = suggestPrCleanup(row.title, row.body);
    if (!suggestion.titleChanged && !(updateBody && suggestion.bodyChanged)) {
      result.skipped++;
      continue;
    }

    result.items.push({
      number: row.number,
      oldTitle: row.title,
      newTitle: suggestion.title,
      bodyUpdated: updateBody && suggestion.bodyChanged,
    });

    if (dryRun) {
      result.updated++;
      continue;
    }

    try {
      if (updateBody && suggestion.body) {
        const bodyFile = path.join(os.tmpdir(), `roland-pr-body-${row.number}-${Date.now()}.md`);
        fs.writeFileSync(bodyFile, suggestion.body, 'utf-8');
        try {
          execSync(
            `gh pr edit ${row.number} --title ${JSON.stringify(suggestion.title)} --body-file ${JSON.stringify(bodyFile)}`,
            { cwd, encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] },
          );
        } finally {
          try { fs.unlinkSync(bodyFile); } catch { /* ignore */ }
        }
      } else {
        execSync(
          `gh pr edit ${row.number} --title ${JSON.stringify(suggestion.title)}`,
          { cwd, encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] },
        );
      }
      result.updated++;
    } catch (e) {
      result.errors.push(
        `PR #${row.number}: ${e instanceof Error ? e.message : String(e)}`,
      );
    }
  }

  return result;
}
