/**
 * PR title & description formatting for Roland task git workflow.
 *
 * Produces conventional-commit style titles (feat/fix/refactor/…) and structured
 * PR bodies without redundant mission prefixes like "Task task-1:" or "[Mission: …]".
 */

import fs from 'fs';
import os from 'os';
import path from 'path';
import { execSync, spawnSync } from 'child_process';

/** Conventional-commit types Roland may emit for autogenerated PRs. */
export type ConventionalCommitType = 'feat' | 'fix' | 'refactor' | 'docs' | 'test' | 'chore';

export interface PrFormatTaskInput {
  id: string;
  title: string;
  agent: string;
  description?: string;
}

export interface PrFormatContext {
  goal: string;
  runId: string;
  missionUrl?: string;
  /** Optional Vanguard / test-executor summary for the Testing section. */
  testingNotes?: string;
  /** Optional one-liner for the Impact section (why this change matters). */
  impactNote?: string;
}

/** Title + body pair returned by formatters. */
export interface FormattedPr {
  title: string;
  body: string;
}

export interface PrCleanupSuggestion {
  title: string;
  body: string | null;
  titleChanged: boolean;
  bodyChanged: boolean;
}

export interface PrCleanupItem {
  number: number;
  oldTitle: string;
  newTitle: string;
  bodyUpdated?: boolean;
}

export interface PrCleanupResult {
  scanned: number;
  updated: number;
  skipped: number;
  dryRun: boolean;
  items: PrCleanupItem[];
  errors: string[];
}

const MAX_PR_TITLE_LEN = 72;

const TYPE_RULES: Array<{ type: ConventionalCommitType; pattern: RegExp }> = [
  { type: 'fix', pattern: /\b(fix|bug|hotfix|patch|resolve|repair|crash|error|broken|regression)\b/i },
  { type: 'refactor', pattern: /\b(refactor|restructure|reorganiz|rename|clean up|extract|simplif)\b/i },
  { type: 'docs', pattern: /\b(document|documentation|readme|guide|comment|spec)\b/i },
  { type: 'test', pattern: /\b(test|coverage|e2e|vitest|jest|regression test|characterization)\b/i },
  { type: 'chore', pattern: /\b(chore|deps|dependency|bump|ci\b|config|tooling|lint)\b/i },
];

const SCOPE_RULES: Array<{ scope: string; pattern: RegExp }> = [
  { scope: 'dashboard', pattern: /\b(dashboard|mobile|responsive|layout|ui|tailwind)\b/i },
  { scope: 'git', pattern: /\b(github|git\b|branch|pull request|\bpr\b|commit)\b/i },
  { scope: 'loop', pattern: /\b(loop[- ]?engine|critique|retry|verification|escalat)\b/i },
  { scope: 'pm', pattern: /\b(pm\b|team|orchestrat|mission|blackboard)\b/i },
  { scope: 'mcp', pattern: /\b(mcp\b|cursor|agent)\b/i },
  { scope: 'api', pattern: /\b(api\b|endpoint|route|middleware|express)\b/i },
  { scope: 'auth', pattern: /\b(auth|login|token|jwt|session)\b/i },
];

const LEGACY_TITLE_PATTERNS = [
  /^Task\s+task[-_]/i,
  /^Roland:\s/i,
  /^\[Mission:/i,
  /^Task[-_]\d+:/i,
];

/** Strip mission/task boilerplate from free text. */
export function stripMissionNoise(text: string): string {
  if (!text?.trim()) return '';
  return text
    .replace(/^\[P\d+\s+active\]\s*/i, '')
    .replace(/\[Mission:\s*[^\]]+\]\s*/gi, '')
    .replace(/\[Mission:\s*[^\]]+\]\s*Team\s+Goal:\s*/gi, '')
    .replace(/Team\s+Goal:\s*/gi, '')
    .replace(/^Task\s+task[-_]?\d+:\s*/i, '')
    .replace(/^Task[-_]?\d+:\s*/i, '')
    .replace(/^Roland:\s*/i, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/** Infer conventional-commit type from task wording. */
export function inferCommitType(title: string, description?: string): ConventionalCommitType {
  const haystack = `${title} ${description ?? ''}`;
  for (const rule of TYPE_RULES) {
    if (rule.pattern.test(haystack)) return rule.type;
  }
  return 'feat';
}

/** Infer a short scope token from task wording. */
export function inferScope(title: string, description?: string): string {
  const haystack = `${title} ${description ?? ''}`;
  for (const rule of SCOPE_RULES) {
    if (rule.pattern.test(haystack)) return rule.scope;
  }
  return 'roland';
}

/** Lowercase imperative subject for conventional commits (no trailing period). */
export function formatCommitSubject(text: string): string {
  const clean = stripMissionNoise(text);
  if (!clean) return 'update roland task output';
  const lowered = clean.charAt(0).toLowerCase() + clean.slice(1);
  return lowered.replace(/[.!?]+$/, '').trim();
}

function truncateTitle(type: string, scope: string, subject: string): string {
  const prefix = `${type}(${scope}): `;
  const maxSubject = MAX_PR_TITLE_LEN - prefix.length;
  if (maxSubject < 8) return `${type}(${scope}): update`.slice(0, MAX_PR_TITLE_LEN);
  const trimmed = subject.length > maxSubject
    ? subject.slice(0, maxSubject - 1).trimEnd() + '…'
    : subject;
  return `${prefix}${trimmed}`;
}

/** Build a conventional-commit PR title from task metadata. */
export function buildConventionalPrTitle(task: PrFormatTaskInput): string {
  const cleanTitle = stripMissionNoise(task.title);
  const subject = formatCommitSubject(cleanTitle || task.title);
  const type = inferCommitType(cleanTitle || task.title, task.description);
  const scope = inferScope(cleanTitle || task.title, task.description);
  return truncateTitle(type, scope, subject);
}

/** True when a PR title uses legacy Roland/mission prefixes. */
export function isLegacyPrTitle(title: string): boolean {
  const t = title?.trim() ?? '';
  if (!t) return false;
  return LEGACY_TITLE_PATTERNS.some((re) => re.test(t));
}

/**
 * Derive a clean conventional title from a legacy PR title (and optional body).
 * Returns null when the title is already clean or cannot be migrated.
 */
export function migrateLegacyPrTitle(title: string, body?: string): string | null {
  const trimmed = title?.trim() ?? '';
  if (!trimmed || !isLegacyPrTitle(trimmed)) return null;

  let seed = stripMissionNoise(trimmed);
  if (!seed && body) {
    const goalMatch = body.match(/\*\*Goal:\*\*\s*(.+)/i)
      ?? body.match(/## Mission Goal\s*\n+(.+)/i)
      ?? body.match(/\*\*Title:\*\*\s*(.+)/i);
    seed = goalMatch ? stripMissionNoise(goalMatch[1]) : '';
  }
  if (!seed) return null;

  return buildConventionalPrTitle({
    id: 'legacy',
    title: seed,
    agent: 'executor',
    description: body,
  });
}

function bulletizeDescription(description: string): string[] {
  const lines = description
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean);
  if (lines.length === 0) return ['Task deliverable as described in the mission plan.'];
  if (lines.length === 1) return [lines[0]];
  return lines.slice(0, 6).map((l) => (l.startsWith('- ') ? l : `- ${l}`));
}

/** Structured markdown PR body for Roland executor tasks. */
export function buildPrDescription(task: PrFormatTaskInput, ctx: PrFormatContext): string {
  const summarySource = stripMissionNoise(task.description ?? '') || stripMissionNoise(task.title);
  const mission = stripMissionNoise(ctx.goal) || ctx.goal.trim();
  const keyChanges = bulletizeDescription(task.description?.trim() || task.title);

  const testing = ctx.testingNotes?.trim()
    || '- Roland PM team workflow (executor task completion + automated git push)\n'
    + '- Manual review recommended before marking PR ready for merge';

  const lines = [
    '## Summary',
    summarySource || 'Implements the scoped Roland team task deliverable.',
    '',
    '## Key changes',
    ...keyChanges,
    '',
    '## Testing',
    testing,
    '',
    '## Related',
    `- **Task:** \`${task.id}\` (${task.agent})`,
  ];

  if (mission) {
    lines.push(`- **Mission:** ${mission}`);
  }
  lines.push(`- **Run:** \`${ctx.runId}\``);

  if (ctx.missionUrl) {
    lines.push(`- **Dashboard:** ${ctx.missionUrl}`);
  }

  if (ctx.impactNote?.trim()) {
    lines.push('', '## Impact', ctx.impactNote.trim());
  }

  lines.push(
    '',
    '---',
    '*Draft PR opened by Roland task git workflow.*',
  );

  return lines.join('\n');
}

/**
 * Build a clean conventional title + structured body from a mission goal.
 * Used by roland-web and manual PR creation paths outside task-git-workflow.
 */
export function formatPrFromGoal(
  goal: string,
  opts?: {
    runId?: string;
    testingNotes?: string;
    impactNote?: string;
    missionUrl?: string;
    agent?: string;
    taskId?: string;
  },
): FormattedPr {
  const cleanGoal = stripMissionNoise(goal) || goal.trim();
  const task: PrFormatTaskInput = {
    id: opts?.taskId ?? 'mission',
    title: cleanGoal,
    agent: opts?.agent ?? 'executor',
    description: cleanGoal,
  };
  const ctx: PrFormatContext = {
    goal: cleanGoal,
    runId: opts?.runId ?? 'roland-run',
    testingNotes: opts?.testingNotes,
    impactNote: opts?.impactNote,
    missionUrl: opts?.missionUrl,
  };
  return {
    title: buildConventionalPrTitle(task),
    body: buildPrDescription(task, ctx),
  };
}

/** True when a PR body uses the legacy "## Roland Run" template without structured sections. */
export function isLegacyPrBody(body: string): boolean {
  const b = body?.trim() ?? '';
  if (!b) return false;
  if (b.includes('## Summary') && b.includes('## Key changes')) return false;
  return /^## Roland Run\b/im.test(b)
    || /^\*\*Goal:\*\*\s/m.test(b)
    || /Generated automatically by Roland/i.test(b);
}

/**
 * Rebuild a structured PR body from a legacy "## Roland Run" template.
 */
export function migrateLegacyPrBody(
  title: string,
  body: string,
  ctx?: Partial<PrFormatContext>,
): string {
  const goalMatch = body.match(/\*\*Goal:\*\*\s*(.+)/i)
    ?? body.match(/## Mission Goal\s*\n+(.+)/i);
  const seed = goalMatch
    ? stripMissionNoise(goalMatch[1])
    : stripMissionNoise(title);
  const task: PrFormatTaskInput = {
    id: ctx?.runId ?? 'legacy',
    title: seed || title,
    agent: 'executor',
    description: seed || title,
  };
  return buildPrDescription(task, {
    goal: seed || title,
    runId: ctx?.runId ?? 'legacy-cleanup',
    missionUrl: ctx?.missionUrl,
    testingNotes: ctx?.testingNotes,
    impactNote: ctx?.impactNote,
  });
}

/** Suggest clean title and body for an existing PR without mutating GitHub. */
export function suggestPrCleanup(title: string, body?: string): PrCleanupSuggestion {
  const trimmedTitle = title?.trim() ?? '';
  const trimmedBody = body?.trim() ?? '';

  let newTitle = trimmedTitle;
  let titleChanged = false;
  if (isLegacyPrTitle(trimmedTitle)) {
    const migrated = migrateLegacyPrTitle(trimmedTitle, trimmedBody);
    if (migrated && migrated !== trimmedTitle) {
      newTitle = migrated;
      titleChanged = true;
    }
  }

  let newBody: string | null = null;
  let bodyChanged = false;
  if (trimmedBody && isLegacyPrBody(trimmedBody)) {
    newBody = migrateLegacyPrBody(newTitle, trimmedBody);
    bodyChanged = newBody !== trimmedBody;
  }

  return { title: newTitle, body: newBody, titleChanged, bodyChanged };
}

/** Conventional commit message body for per-task git commits. */
export function buildTaskCommitMessage(task: PrFormatTaskInput): string {
  const title = buildConventionalPrTitle(task);
  return [
    title,
    '',
    `Closes task ${task.id}`,
    '',
    'Generated by Roland',
  ].join('\n');
}

function ghAvailable(): boolean {
  try {
    const r = spawnSync('gh', ['--version'], { stdio: 'ignore' });
    return r.status === 0;
  } catch {
    return false;
  }
}

/** Fetch the open PR for the current git branch via `gh`, if any. */
export function getCurrentPrFromGh(cwd: string): { number: number; title: string; body: string } | null {
  if (!ghAvailable()) return null;
  try {
    const json = execSync(
      'gh pr view --json number,title,body',
      { cwd, encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] },
    );
    const row = JSON.parse(json) as { number?: number; title?: string; body?: string };
    if (!row.number || !row.title) return null;
    return { number: row.number, title: row.title, body: row.body ?? '' };
  } catch {
    return null;
  }
}

/**
 * Format (or preview formatting for) the PR on the current branch.
 * Updates title and/or body when legacy patterns are detected.
 */
export function formatCurrentPr(
  cwd: string,
  opts?: { dryRun?: boolean; updateBody?: boolean },
): PrCleanupResult {
  const dryRun = opts?.dryRun ?? false;
  const updateBody = opts?.updateBody ?? true;
  const result: PrCleanupResult = {
    scanned: 0,
    updated: 0,
    skipped: 0,
    dryRun,
    items: [],
    errors: [],
  };

  if (!ghAvailable()) {
    result.errors.push('`gh` CLI not found — install from https://cli.github.com/');
    return result;
  }

  const row = getCurrentPrFromGh(cwd);
  if (!row) {
    result.errors.push('No open PR found for the current branch — create one or pass a PR number');
    return result;
  }

  result.scanned = 1;
  return applyPrCleanupSuggestion(cwd, row, { dryRun, updateBody, result });
}

function applyPrCleanupSuggestion(
  cwd: string,
  row: { number: number; title: string; body: string },
  opts: { dryRun: boolean; updateBody: boolean; result: PrCleanupResult },
): PrCleanupResult {
  const { dryRun, updateBody, result } = opts;
  const suggestion = suggestPrCleanup(row.title, row.body);

  if (!suggestion.titleChanged && !(updateBody && suggestion.bodyChanged)) {
    result.skipped++;
    return result;
  }

  result.items.push({
    number: row.number,
    oldTitle: row.title,
    newTitle: suggestion.title,
    bodyUpdated: updateBody && suggestion.bodyChanged,
  });

  if (dryRun) {
    result.updated++;
    return result;
  }

  try {
    const args = ['pr', 'edit', String(row.number), '--title', suggestion.title];
    if (updateBody && suggestion.body) {
      const bodyFile = path.join(os.tmpdir(), `roland-pr-body-${row.number}-${Date.now()}.md`);
      fs.writeFileSync(bodyFile, suggestion.body, 'utf-8');
      try {
        execSync(
          `gh pr edit ${row.number} --title ${JSON.stringify(suggestion.title)} --body-file ${JSON.stringify(bodyFile)}`,
          { cwd, encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] },
        );
      } finally {
        try { fs.unlinkSync(bodyFile); } catch { /* ignore */ }
      }
    } else {
      execSync(
        `gh pr edit ${row.number} --title ${JSON.stringify(suggestion.title)}`,
        { cwd, encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] },
      );
    }
    result.updated++;
  } catch (e) {
    result.errors.push(
      `PR #${row.number}: ${e instanceof Error ? e.message : String(e)}`,
    );
  }

  return result;
}

/**
 * Best-effort batch rename of recent open PRs with legacy titles via `gh pr edit`.
 * Safe to run with --dry-run; skips PRs that already match the convention.
 */
export function cleanupLegacyPrTitles(
  cwd: string,
  opts?: { limit?: number; dryRun?: boolean; updateBody?: boolean; prNumber?: number },
): PrCleanupResult {
  const limit = Math.max(1, Math.min(opts?.limit ?? 20, 100));
  const dryRun = opts?.dryRun ?? false;
  const result: PrCleanupResult = {
    scanned: 0,
    updated: 0,
    skipped: 0,
    dryRun,
    items: [],
    errors: [],
  };

  if (!ghAvailable()) {
    result.errors.push('`gh` CLI not found — install from https://cli.github.com/');
    return result;
  }

  let rows: Array<{ number: number; title: string; body: string }>;
  try {
    const json = execSync(
      `gh pr list --state open --limit ${limit} --json number,title,body`,
      { cwd, encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] },
    );
    rows = JSON.parse(json) as Array<{ number: number; title: string; body: string }>;
  } catch (e) {
    result.errors.push(e instanceof Error ? e.message : String(e));
    return result;
  }

  const updateBody = opts?.updateBody ?? false;

  if (opts?.prNumber) {
    const match = rows.find((r) => r.number === opts.prNumber);
    if (!match) {
      result.errors.push(`PR #${opts.prNumber} not found among open PRs (limit ${limit})`);
      return result;
    }
    result.scanned = 1;
    return applyPrCleanupSuggestion(cwd, match, { dryRun, updateBody, result });
  }

  for (const row of rows) {
    result.scanned++;
    const suggestion = suggestPrCleanup(row.title, row.body);
    if (!suggestion.titleChanged && !(updateBody && suggestion.bodyChanged)) {
      result.skipped++;
      continue;
    }

    result.items.push({
      number: row.number,
      oldTitle: row.title,
      newTitle: suggestion.title,
      bodyUpdated: updateBody && suggestion.bodyChanged,
    });

    if (dryRun) {
      result.updated++;
      continue;
    }

    try {
      if (updateBody && suggestion.body) {
        const bodyFile = path.join(os.tmpdir(), `roland-pr-body-${row.number}-${Date.now()}.md`);
        fs.writeFileSync(bodyFile, suggestion.body, 'utf-8');
        try {
          execSync(
            `gh pr edit ${row.number} --title ${JSON.stringify(suggestion.title)} --body-file ${JSON.stringify(bodyFile)}`,
            { cwd, encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] },
          );
        } finally {
          try { fs.unlinkSync(bodyFile); } catch { /* ignore */ }
        }
      } else {
        execSync(
          `gh pr edit ${row.number} --title ${JSON.stringify(suggestion.title)}`,
          { cwd, encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] },
        );
      }
      result.updated++;
    } catch (e) {
      result.errors.push(
        `PR #${row.number}: ${e instanceof Error ? e.message : String(e)}`,
      );
    }
  }

  return result;
}
